<?php
/*--------------------------------------------------------------------------------------
|
|	Archivo:	footer.inc
|	Autor:		Saúl E Morales Cedillo (ccedillo@df.gob.mx)
|	Fecha:		Noviembre 2002
|
|	Gobierno del Distrito Federal
|	Oficialía Mayor
|	Coordinación Ejecutiva de Desarrollo Informático
|	Dirección de Nuevas Tecnologías
|
|	Última actualización:	04/11/2002
|
--------------------------------------------------------------------------------------*/
?>
	  </tr>
 	 </table>
	</td>
 </tr>
</table>
<br>
</body>
</html>

